language: go

before_install:
  - go get git.apache.org/thrift.git/lib/go/thrift
  - go get github.com/nats-io/nats
  - go get github.com/nats-io/gnatsd

script: go test ./...

notifications:
  email: false
